self.a = u.parseIntegerOpt(data, base, path, {"a"}, 2)
self.b = u.parseNumberOpt(data, base, path, {"b"}, -3.14)
self.c = u.parseBooleanOpt(data, base, path, {"c"}, false)
self.d = u.parseBooleanOpt(data, base, path, {"d"}, true)
self.e = u.parseStringOpt(data, base, path, {"e"}, "Hello, World!")
self.f = u.parseVec2Opt(data, base, path, {"f"}, Vec2(-2.5, 6))
self.g = u.parseExprNumberOpt(data, base, path, {"g"}, 1)
self.h = u.parseExprVec2Opt(data, base, path, {"h"}, Vec2(-420, 69))