self.a = u.parseInteger(data, base, path, {"a"}, 2)
self.b = u.parseNumber(data, base, path, {"b"}, -3.14)
self.c = u.parseBoolean(data, base, path, {"c"}, false)
self.d = u.parseBoolean(data, base, path, {"d"}, true)
self.e = u.parseString(data, base, path, {"e"}, "Hello, World!")
self.f = u.parseVec2(data, base, path, {"f"}, Vec2(-2.5, 6))
self.g = u.parseExprNumber(data, base, path, {"g"}, 1)
self.h = u.parseExprVec2(data, base, path, {"h"}, Vec2(-420, 69))