--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class CollectibleGeneratorConfig
---@overload fun(data, path):CollectibleGeneratorConfig
local CollectibleGeneratorConfig = class:derive("CollectibleGeneratorConfig")

CollectibleGeneratorConfig.metadata = {
    schemaPath = "collectible_generator.json"
}

---Constructs an instance of CollectibleGeneratorConfig.
---@param data table Raw data from a file.
---@param path string Path to the file. The file is not loaded here, and it is not used in error messages, but some classes use it for saving data. TODO: Find an alternative.
function CollectibleGeneratorConfig:new(data, path)
    local u = _ConfigUtils
    self._path = path

    self.type = u.parseString(data.type, path, "type")
    if self.type == "collectible" then
        self.name = u.parseString(data.name, path, "name")
    elseif self.type == "collectibleGenerator" then
        self.generator = u.parseCollectibleGeneratorConfig(data.generator, path, "generator")
    elseif self.type == "combine" then
        self.entries = {}
        for i = 1, #data.entries do
            self.entries[i] = u.parseCollectibleGeneratorConfig(data.entries[i], path, "entries[" .. tostring(i) .. "]")
        end
    elseif self.type == "repeat" then
        self.entry = u.parseCollectibleGeneratorConfig(data.entry, path, "entry")
        self.count = u.parseExprInteger(data.count, path, "count")
    elseif self.type == "randomPick" then
        self.pool = {}
        for i = 1, #data.pool do
            self.pool[i] = {}
            self.pool[i].entry = u.parseCollectibleGeneratorConfig(data.pool[i].entry, path, "pool[" .. tostring(i) .. "].entry")
            self.pool[i].weight = u.parseNumberOpt(data.pool[i].weight, path, "pool[" .. tostring(i) .. "].weight")
        end
    else
        error(string.format("Unknown CollectibleGeneratorConfig type: %s (expected \"collectible\", \"collectibleGenerator\", \"combine\", \"repeat\", \"randomPick\")", self.type))
    end

    self.conditions = {}
    if data.conditions then
        for i = 1, #data.conditions do
            self.conditions[i] = u.parseExprBoolean(data.conditions[i], path, "conditions[" .. tostring(i) .. "]")
        end
    end
end

---Injects functions to Resource Manager regarding this resource type.
---@param ResourceManager ResourceManager Resource Manager class to inject the functions to.
function CollectibleGeneratorConfig.inject(ResourceManager)
    ---@class ResourceManager
    ResourceManager = ResourceManager

    ---Retrieves a CollectibleGeneratorConfig by a given path.
    ---@param path string The resource path.
    ---@return CollectibleGeneratorConfig
    function ResourceManager:getCollectibleGeneratorConfig(path)
        return self:getResourceConfig(path, "CollectibleGeneratorConfig")
    end
end

return CollectibleGeneratorConfig