--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class CollectibleGeneratorConfig
---@overload fun(data, path, isAnonymous):CollectibleGeneratorConfig
local CollectibleGeneratorConfig = class:derive("CollectibleGeneratorConfig")

CollectibleGeneratorConfig.metadata = {
    schemaPath = "collectible_generator.json"
}

---Constructs an instance of CollectibleGeneratorConfig.
---@param data table Raw data from a file.
---@param path string? Path to the file. Used for error messages and saving data.
---@param isAnonymous boolean? If `true`, this resource is anonymous and its path is invalid for saving data.
---@param base CollectibleGeneratorConfig? If specified, this resource extends the provided resource. Any missing fields are prepended from the base resource.
function CollectibleGeneratorConfig:new(data, path, isAnonymous, base)
    local u = _ConfigUtils
    self._path = path
    self._alias = data._alias
    self._isAnonymous = isAnonymous

    base = base or {}

    self.type = u.parseString(data, base, path, {"type"})
    if self.type == "collectible" then
        self.collectible = u.parseCollectibleConfig(data, base, path, {"collectible"})
    elseif self.type == "collectibleGenerator" then
        self.generator = u.parseCollectibleGeneratorConfig(data, base, path, {"generator"})
    elseif self.type == "combine" then
        self.entries = {}
        for i = 1, #data.entries do
            self.entries[i] = u.parseCollectibleGeneratorConfig(data, base, path, {"entries", i})
        end
    elseif self.type == "repeat" then
        self.entry = u.parseCollectibleGeneratorConfig(data, base, path, {"entry"})
        self.count = u.parseExprInteger(data, base, path, {"count"})
    elseif self.type == "randomPick" then
        self.pool = {}
        for i = 1, #data.pool do
            self.pool[i] = {}
            self.pool[i].entry = u.parseCollectibleGeneratorConfig(data, base, path, {"pool", i, "entry"})
            self.pool[i].weight = u.parseNumberOpt(data, base, path, {"pool", i, "weight"})
        end
    else
        error(string.format("Unknown CollectibleGeneratorConfig type: %s (expected \"collectible\", \"collectibleGenerator\", \"combine\", \"repeat\", \"randomPick\")", self.type))
    end

    self.conditions = {}
    if data.conditions then
        for i = 1, #data.conditions do
            self.conditions[i] = u.parseExprBoolean(data, base, path, {"conditions", i})
        end
    end
end

---Injects functions to Resource Manager regarding this resource type.
---@param ResourceManager ResourceManager Resource Manager class to inject the functions to.
function CollectibleGeneratorConfig.inject(ResourceManager)
    ---@class ResourceManager
    ResourceManager = ResourceManager

    ---Retrieves a CollectibleGeneratorConfig by given path.
    ---@param reference string The path to the resource.
    ---@return CollectibleGeneratorConfig
    function ResourceManager:getCollectibleGeneratorConfig(reference)
        return self:getResourceConfig(reference, "CollectibleGenerator")
    end
end

return CollectibleGeneratorConfig