--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class GameEventConfig
---@overload fun(data, path):GameEventConfig
local GameEventConfig = class:derive("GameEventConfig")



---Constructs an instance of GameEventConfig.
---@param data table Raw data from a file.
---@param path string Path to the file. The file is not loaded here, and it is not used in error messages, but some classes use it for saving data. TODO: Find an alternative.
function GameEventConfig:new(data, path)
    local u = _ConfigUtils
    self._path = path

    self.type = u.parseString(data.type, path, "type")
    if self.type == "sequence" then
        self.events = {}
        for i = 1, #data.events do
            self.events[i] = u.parseGameEventConfig(data.events[i], path, "events[" .. tostring(i) .. "]")
        end
    elseif self.type == "random" then
        self.events = {}
        for i = 1, #data.events do
            self.events[i] = u.parseGameEventConfig(data.events[i], path, "events[" .. tostring(i) .. "]")
        end
    elseif self.type == "setCoins" then
        self.value = u.parseExprInteger(data.value, path, "value")
    elseif self.type == "setLevelVariable" then
        self.variable = u.parseString(data.variable, path, "variable")
        self.value = u.parseExprNumber(data.value, path, "value")
    elseif self.type == "setLevelTimer" then
        self.timer = u.parseString(data.timer, path, "timer")
        self.time = u.parseExprNumberOpt(data.time, path, "time") or 0
    elseif self.type == "addToTimerSeries" then
        self.timerSeries = u.parseString(data.timerSeries, path, "timerSeries")
        self.time = u.parseExprNumber(data.time, path, "time")
    elseif self.type == "clearTimerSeries" then
        self.timerSeries = u.parseString(data.timerSeries, path, "timerSeries")
    elseif self.type == "collectibleEffect" then
        self.collectibleEffect = u.parseCollectibleEffectConfig(data.collectibleEffect, path, "collectibleEffect")
    elseif self.type == "scoreEvent" then
        self.scoreEvent = u.parseScoreEventConfig(data.scoreEvent, path, "scoreEvent")
    elseif self.type == "playSound" then
        self.soundEvent = u.parseSoundEvent(data.soundEvent, path, "soundEvent")
    else
        error(string.format("Unknown GameEventConfig type: %s (expected \"sequence\", \"random\", \"setCoins\", \"setLevelVariable\", \"setLevelTimer\", \"addToTimerSeries\", \"clearTimerSeries\", \"collectibleEffect\", \"scoreEvent\", \"playSound\")", self.type))
    end

    self.conditions = {}
    if data.conditions then
        for i = 1, #data.conditions do
            self.conditions[i] = u.parseExprBoolean(data.conditions[i], path, "conditions[" .. tostring(i) .. "]")
        end
    end
end



return GameEventConfig