--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class GameConfig
---@overload fun(data, path, isAnonymous):GameConfig
local GameConfig = class:derive("GameConfig")

GameConfig.metadata = {
    schemaPath = "game.json"
}

---Constructs an instance of GameConfig.
---@param data table Raw data from a file.
---@param path string? Path to the file. Used for error messages and saving data.
---@param isAnonymous boolean? If `true`, this resource is anonymous and its path is invalid for saving data.
---@param base GameConfig? If specified, this resource extends the provided resource. Any missing fields are prepended from the base resource.
function GameConfig:new(data, path, isAnonymous, base)
    local u = _ConfigUtils
    self._path = path
    self._alias = data._alias
    self._isAnonymous = isAnonymous

    base = base or {}

    self.name = u.parseStringOpt(data, base, path, {"name"})
    self.windowTitle = u.parseStringOpt(data, base, path, {"windowTitle"})
    self.engineVersion = u.parseString(data, base, path, {"engineVersion"})
    self.nativeResolution = u.parseVec2(data, base, path, {"nativeResolution"})
    self.tickRate = u.parseIntegerOpt(data, base, path, {"tickRate"}, 60)
    self.canvasRenderingMode = u.parseStringOpt(data, base, path, {"canvasRenderingMode"}, "filtered")

    if data.richPresence then
        self.richPresence = {}
        self.richPresence.enabled = u.parseBoolean(data, base, path, {"richPresence", "enabled"})
        self.richPresence.applicationID = u.parseStringOpt(data, base, path, {"richPresence", "applicationID"})
    end
end

---Injects functions to Resource Manager regarding this resource type.
---@param ResourceManager ResourceManager Resource Manager class to inject the functions to.
function GameConfig.inject(ResourceManager)
    ---@class ResourceManager
    ResourceManager = ResourceManager

    ---Retrieves a GameConfig by given path.
    ---@param reference string The path to the resource.
    ---@return GameConfig
    function ResourceManager:getGameConfig(reference)
        return self:getResourceConfig(reference, "Game")
    end
end

return GameConfig