--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class HighscoresConfig
---@overload fun(data, path, isAnonymous):HighscoresConfig
local HighscoresConfig = class:derive("HighscoresConfig")

HighscoresConfig.metadata = {
    schemaPath = "config/highscores.json"
}

---Constructs an instance of HighscoresConfig.
---@param data table Raw data from a file.
---@param path string? Path to the file. Used for error messages and saving data.
---@param isAnonymous boolean? If `true`, this resource is anonymous and its path is invalid for saving data.
---@param base HighscoresConfig? If specified, this resource extends the provided resource. Any missing fields are prepended from the base resource.
function HighscoresConfig:new(data, path, isAnonymous, base)
    local u = _ConfigUtils
    self._path = path
    self._alias = data._alias
    self._isAnonymous = isAnonymous

    base = base or {}

    self.size = u.parseInteger(data, base, path, {"size"})

    ---@type {name: string, score: integer, level: string}[]
    self.defaultScores = {}
    for i = 1, #data.defaultScores do
        self.defaultScores[i] = {}
        self.defaultScores[i].name = u.parseString(data, base, path, {"defaultScores", i, "name"})
        self.defaultScores[i].score = u.parseInteger(data, base, path, {"defaultScores", i, "score"})
        self.defaultScores[i].level = u.parseString(data, base, path, {"defaultScores", i, "level"})
    end
end

---Injects functions to Resource Manager regarding this resource type.
---@param ResourceManager ResourceManager Resource Manager class to inject the functions to.
function HighscoresConfig.inject(ResourceManager)
    ---@class ResourceManager
    ResourceManager = ResourceManager

    ---Retrieves a HighscoresConfig by given path.
    ---@param reference string The path to the resource.
    ---@return HighscoresConfig
    function ResourceManager:getHighscoresConfig(reference)
        return self:getResourceConfig(reference, "Highscores")
    end
end

return HighscoresConfig