--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class LayersConfig
---@overload fun(data, path, isAnonymous):LayersConfig
local LayersConfig = class:derive("LayersConfig")

LayersConfig.metadata = {
    schemaPath = "config/layers.json"
}

---Constructs an instance of LayersConfig.
---@param data table Raw data from a file.
---@param path string? Path to the file. Used for error messages and saving data.
---@param isAnonymous boolean? If `true`, this resource is anonymous and its path is invalid for saving data.
---@param base LayersConfig? If specified, this resource extends the provided resource. Any missing fields are prepended from the base resource.
function LayersConfig:new(data, path, isAnonymous, base)
    local u = _ConfigUtils
    self._path = path
    self._alias = data._alias
    self._isAnonymous = isAnonymous

    base = base or {}

    ---@type string[]
    self.layers = {}
    for i = 1, #data.layers do
        self.layers[i] = u.parseString(data, base, path, {"layers", i})
    end
end

---Injects functions to Resource Manager regarding this resource type.
---@param ResourceManager ResourceManager Resource Manager class to inject the functions to.
function LayersConfig.inject(ResourceManager)
    ---@class ResourceManager
    ResourceManager = ResourceManager

    ---Retrieves a LayersConfig by given path.
    ---@param reference string The path to the resource.
    ---@return LayersConfig
    function ResourceManager:getLayersConfig(reference)
        return self:getResourceConfig(reference, "Layers")
    end
end

return LayersConfig