--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class LocaleConfig
---@overload fun(data, path, isAnonymous):LocaleConfig
local LocaleConfig = class:derive("LocaleConfig")

LocaleConfig.metadata = {
    schemaPath = "locale.json"
}

---Constructs an instance of LocaleConfig.
---@param data table Raw data from a file.
---@param path string? Path to the file. Used for error messages and saving data.
---@param isAnonymous boolean? If `true`, this resource is anonymous and its path is invalid for saving data.
---@param base LocaleConfig? If specified, this resource extends the provided resource. Any missing fields are prepended from the base resource.
function LocaleConfig:new(data, path, isAnonymous, base)
    local u = _ConfigUtils
    self._path = path
    self._alias = data._alias
    self._isAnonymous = isAnonymous

    base = base or {}

    ---@type table<string, string>
    self.keys = {}
    for n, _ in pairs(data.keys) do
        self.keys[n] = u.parseString(data, base, path, {"keys", n})
    end
end

---Injects functions to Resource Manager regarding this resource type.
---@param ResourceManager ResourceManager Resource Manager class to inject the functions to.
function LocaleConfig.inject(ResourceManager)
    ---@class ResourceManager
    ResourceManager = ResourceManager

    ---Retrieves a LocaleConfig by given path.
    ---@param reference string The path to the resource.
    ---@return LocaleConfig
    function ResourceManager:getLocaleConfig(reference)
        return self:getResourceConfig(reference, "Locale")
    end
end

return LocaleConfig