--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class MapConfig
---@overload fun(data, path, isAnonymous):MapConfig
local MapConfig = class:derive("MapConfig")

MapConfig.metadata = {
    schemaPath = "map.json"
}

---Constructs an instance of MapConfig.
---@param data table Raw data from a file.
---@param path string? Path to the file. Used for error messages and saving data.
---@param isAnonymous boolean? If `true`, this resource is anonymous and its path is invalid for saving data.
---@param base MapConfig? If specified, this resource extends the provided resource. Any missing fields are prepended from the base resource.
function MapConfig:new(data, path, isAnonymous, base)
    local u = _ConfigUtils
    self._path = path
    self._alias = data._alias
    self._isAnonymous = isAnonymous

    base = base or {}

    self.name = u.parseString(data, base, path, {"name"})

    ---@type PathConfig[]
    self.paths = {}
    for i = 1, #data.paths do
        self.paths[i] = u.parsePathConfig(data, base, path, {"paths", i})
    end

    ---@type table[]
    self.objects = {}
    for i = 1, #data.objects do
        self.objects[i] = {}
        self.objects[i].type = u.parseString(data, base, path, {"objects", i, "type"})
        if self.objects[i].type == "sprite" then
            self.objects[i].sprite = u.parseSprite(data, base, path, {"objects", i, "sprite"})
        elseif self.objects[i].type == "particle" then
            self.objects[i].particle = u.parseParticleEffectConfig(data, base, path, {"objects", i, "particle"})
        else
            error(string.format("Unknown MapConfig type: %s (expected \"sprite\", \"particle\")", self.objects[i].type))
        end
        self.objects[i].layer = u.parseString(data, base, path, {"objects", i, "layer"})
        self.objects[i].x = u.parseNumber(data, base, path, {"objects", i, "x"})
        self.objects[i].y = u.parseNumber(data, base, path, {"objects", i, "y"})
    end
end

---Injects functions to Resource Manager regarding this resource type.
---@param ResourceManager ResourceManager Resource Manager class to inject the functions to.
function MapConfig.inject(ResourceManager)
    ---@class ResourceManager
    ResourceManager = ResourceManager

    ---Retrieves a MapConfig by given path.
    ---@param reference string The path to the resource.
    ---@return MapConfig
    function ResourceManager:getMapConfig(reference)
        return self:getResourceConfig(reference, "Map")
    end
end

return MapConfig