--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class MusicPlaylistConfig
---@overload fun(data, path, isAnonymous):MusicPlaylistConfig
local MusicPlaylistConfig = class:derive("MusicPlaylistConfig")

MusicPlaylistConfig.metadata = {
    schemaPath = "music_playlist.json"
}

---Constructs an instance of MusicPlaylistConfig.
---@param data table Raw data from a file.
---@param path string? Path to the file. Used for error messages and saving data.
---@param isAnonymous boolean? If `true`, this resource is anonymous and its path is invalid for saving data.
---@param base MusicPlaylistConfig? If specified, this resource extends the provided resource. Any missing fields are prepended from the base resource.
function MusicPlaylistConfig:new(data, path, isAnonymous, base)
    local u = _ConfigUtils
    self._path = path
    self._alias = data._alias
    self._isAnonymous = isAnonymous

    base = base or {}

    ---@type MusicTrack[]
    self.tracks = {}
    for i = 1, #data.tracks do
        self.tracks[i] = u.parseMusicTrack(data, base, path, {"tracks", i})
    end

    ---@type "random"|"sequence"
    self.order = u.parseStringOpt(data, base, path, {"order"}, "random")
end

---Injects functions to Resource Manager regarding this resource type.
---@param ResourceManager ResourceManager Resource Manager class to inject the functions to.
function MusicPlaylistConfig.inject(ResourceManager)
    ---@class ResourceManager
    ResourceManager = ResourceManager

    ---Retrieves a MusicPlaylistConfig by given path.
    ---@param reference string The path to the resource.
    ---@return MusicPlaylistConfig
    function ResourceManager:getMusicPlaylistConfig(reference)
        return self:getResourceConfig(reference, "MusicPlaylist")
    end
end

return MusicPlaylistConfig