--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class MusicTrackConfig
---@overload fun(data, path, isAnonymous):MusicTrackConfig
local MusicTrackConfig = class:derive("MusicTrackConfig")

MusicTrackConfig.metadata = {
    schemaPath = "music_track.json"
}

---Constructs an instance of MusicTrackConfig.
---@param data table Raw data from a file.
---@param path string? Path to the file. Used for error messages and saving data.
---@param isAnonymous boolean? If `true`, this resource is anonymous and its path is invalid for saving data.
---@param base MusicTrackConfig? If specified, this resource extends the provided resource. Any missing fields are prepended from the base resource.
function MusicTrackConfig:new(data, path, isAnonymous, base)
    local u = _ConfigUtils
    self._path = path
    self._alias = data._alias
    self._isAnonymous = isAnonymous

    base = base or {}

    self.audio = u.parseSound(data, base, path, {"audio"})
end

---Injects functions to Resource Manager regarding this resource type.
---@param ResourceManager ResourceManager Resource Manager class to inject the functions to.
function MusicTrackConfig.inject(ResourceManager)
    ---@class ResourceManager
    ResourceManager = ResourceManager

    ---Retrieves a MusicTrackConfig by given path.
    ---@param reference string The path to the resource.
    ---@return MusicTrackConfig
    function ResourceManager:getMusicTrackConfig(reference)
        return self:getResourceConfig(reference, "MusicTrack")
    end
end

return MusicTrackConfig