--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class ParticleEmitterConfig
---@overload fun(data, path, isAnonymous):ParticleEmitterConfig
local ParticleEmitterConfig = class:derive("ParticleEmitterConfig")

ParticleEmitterConfig.metadata = {
    schemaPath = "particle_emitter.json"
}

---Constructs an instance of ParticleEmitterConfig.
---@param data table Raw data from a file.
---@param path string? Path to the file. Used for error messages and saving data.
---@param isAnonymous boolean? If `true`, this resource is anonymous and its path is invalid for saving data.
function ParticleEmitterConfig:new(data, path, isAnonymous)
    local u = _ConfigUtils
    self._path = path
    self._alias = data._alias
    self._isAnonymous = isAnonymous

    self.pos = u.parseVec2(data.pos, path, "pos")
    self.speed = u.parseVec2(data.speed, path, "speed")
    self.acceleration = u.parseVec2(data.acceleration, path, "acceleration")
    self.lifespan = u.parseNumberOpt(data.lifespan, path, "lifespan")
    self.spawnCount = u.parseInteger(data.spawnCount, path, "spawnCount")
    self.spawnMax = u.parseInteger(data.spawnMax, path, "spawnMax")
    self.spawnDelay = u.parseNumberOpt(data.spawnDelay, path, "spawnDelay")
    self.particleData = u.parseParticleConfig(data.particleData, path, "particleData")
end

---Injects functions to Resource Manager regarding this resource type.
---@param ResourceManager ResourceManager Resource Manager class to inject the functions to.
function ParticleEmitterConfig.inject(ResourceManager)
    ---@class ResourceManager
    ResourceManager = ResourceManager

    ---Retrieves a ParticleEmitterConfig by given path.
    ---@param reference string The path to the resource.
    ---@return ParticleEmitterConfig
    function ResourceManager:getParticleEmitterConfig(reference)
        return self:getResourceConfig(reference, "ParticleEmitter")
    end
end

return ParticleEmitterConfig