--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class ScoreEventConfig
---@overload fun(data, path):ScoreEventConfig
local ScoreEventConfig = class:derive("ScoreEventConfig")

ScoreEventConfig.metadata = {
    schemaPath = "score_event.json"
}

---Constructs an instance of ScoreEventConfig.
---@param data table Raw data from a file.
---@param path string Path to the file. The file is not loaded here, and it is not used in error messages, but some classes use it for saving data. TODO: Find an alternative.
function ScoreEventConfig:new(data, path)
    local u = _ConfigUtils
    self._path = path

    self.score = u.parseExprInteger(data.score, path, "score")
    self.ignoreDifficultyMultiplier = u.parseBooleanOpt(data.ignoreDifficultyMultiplier, path, "ignoreDifficultyMultiplier")
    self.text = u.parseExprStringOpt(data.text, path, "text")
    self.font = u.parseFontOpt(data.font, path, "font")

    if data.fonts then
        self.fonts = {}

        self.fonts.options = {}
        for i = 1, #data.fonts.options do
            self.fonts.options[i] = u.parseFont(data.fonts.options[i], path, "fonts.options[" .. tostring(i) .. "]")
        end

        self.fonts.default = u.parseFont(data.fonts.default, path, "fonts.default")
        self.fonts.choice = u.parseExprInteger(data.fonts.choice, path, "fonts.choice")
    end
end

---Injects functions to Resource Manager regarding this resource type.
---@param ResourceManager ResourceManager Resource Manager class to inject the functions to.
function ScoreEventConfig.inject(ResourceManager)
    ---@class ResourceManager
    ResourceManager = ResourceManager

    ---Retrieves a ScoreEventConfig by a given path.
    ---@param path string The resource path.
    ---@return ScoreEventConfig
    function ResourceManager:getScoreEventConfig(path)
        return self:getResourceConfig(path, "ScoreEventConfig")
    end
end

return ScoreEventConfig