--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class ShooterMovementConfig
---@overload fun(data, path, isAnonymous):ShooterMovementConfig
local ShooterMovementConfig = class:derive("ShooterMovementConfig")

ShooterMovementConfig.metadata = {
    schemaPath = "shooter_movement.json"
}

---Constructs an instance of ShooterMovementConfig.
---@param data table Raw data from a file.
---@param path string? Path to the file. Used for error messages and saving data.
---@param isAnonymous boolean? If `true`, this resource is anonymous and its path is invalid for saving data.
function ShooterMovementConfig:new(data, path, isAnonymous)
    local u = _ConfigUtils
    self._path = path
    self._alias = data._alias
    self._isAnonymous = isAnonymous

    self.type = u.parseString(data.type, path, "type")
    if self.type == "linear" then
        self.xMin = u.parseNumber(data.xMin, path, "xMin")
        self.xMax = u.parseNumber(data.xMax, path, "xMax")
        self.y = u.parseNumber(data.y, path, "y")
        self.angle = u.parseNumber(data.angle, path, "angle")
    elseif self.type == "circular" then
        self.x = u.parseNumber(data.x, path, "x")
        self.y = u.parseNumber(data.y, path, "y")
    else
        error(string.format("Unknown ShooterMovementConfig type: %s (expected \"linear\", \"circular\")", self.type))
    end
end

---Injects functions to Resource Manager regarding this resource type.
---@param ResourceManager ResourceManager Resource Manager class to inject the functions to.
function ShooterMovementConfig.inject(ResourceManager)
    ---@class ResourceManager
    ResourceManager = ResourceManager

    ---Retrieves a ShooterMovementConfig by a given path or alias.
    ---@param reference string|integer The path or an alias to the resource.
    ---@param skipAliasResolutionCheck boolean? If set, the resource will be returned even if it has unresolved alias references. You should only set this to `true` if you do not intend to interact with the config's contents.
    ---@return ShooterMovementConfig
    function ResourceManager:getShooterMovementConfig(reference, skipAliasResolutionCheck)
        return self:getResourceConfig(reference, "ShooterMovementConfig", skipAliasResolutionCheck)
    end
end

return ShooterMovementConfig