--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"
local Vec2 = require("src.Essentials.Vector2")

---@class ShooterConfig
---@overload fun(data, path, isAnonymous):ShooterConfig
local ShooterConfig = class:derive("ShooterConfig")

ShooterConfig.metadata = {
    schemaPath = "shooter.json"
}

---Constructs an instance of ShooterConfig.
---@param data table Raw data from a file.
---@param path string? Path to the file. Used for error messages and saving data.
---@param isAnonymous boolean? If `true`, this resource is anonymous and its path is invalid for saving data.
---@param base ShooterConfig? If specified, this resource extends the provided resource. Any missing fields are prepended from the base resource.
function ShooterConfig:new(data, path, isAnonymous, base)
    local u = _ConfigUtils
    self._path = path
    self._alias = data._alias
    self._isAnonymous = isAnonymous

    base = base or {}

    self.movement = u.parseShooterMovementConfig(data, base, path, {"movement"})

    ---@type {sprite: Sprite, layer: string, offset: Vector2, anchor: Vector2, animationSpeed: number?, conditions: Expression[]}[]
    self.sprites = {}
    for i = 1, #data.sprites do
        self.sprites[i] = {}
        self.sprites[i].sprite = u.parseSprite(data, base, path, {"sprites", i, "sprite"})
        self.sprites[i].layer = u.parseString(data, base, path, {"sprites", i, "layer"})
        self.sprites[i].offset = u.parseVec2Opt(data, base, path, {"sprites", i, "offset"}, Vec2())
        self.sprites[i].anchor = u.parseVec2Opt(data, base, path, {"sprites", i, "anchor"}, Vec2(0.5, 0.5))
        self.sprites[i].animationSpeed = u.parseNumberOpt(data, base, path, {"sprites", i, "animationSpeed"})

        ---@type Expression[]
        self.sprites[i].conditions = {}
        if data.sprites[i].conditions then
            for j = 1, #data.sprites[i].conditions do
                self.sprites[i].conditions[j] = u.parseExprBoolean(data, base, path, {"sprites", i, "conditions", j})
            end
        end
    end

    ---@type {pos: Vector2, shotPos: Vector2?}[]
    self.spheres = {}
    for i = 1, #data.spheres do
        self.spheres[i] = {}
        self.spheres[i].pos = u.parseVec2(data, base, path, {"spheres", i, "pos"})
        self.spheres[i].shotPos = u.parseVec2Opt(data, base, path, {"spheres", i, "shotPos"})
    end

    ---@type {sprite: Sprite?, offset: Vector2?, nextBallSprite: Sprite?, nextBallOffset: Vector2?, radiusSprite: Sprite?, colorFadeTime: number?, nextColorFadeTime: number?}
    self.reticle = {}
    if data.reticle then
        self.reticle.sprite = u.parseSpriteOpt(data, base, path, {"reticle", "sprite"})
        self.reticle.offset = u.parseVec2Opt(data, base, path, {"reticle", "offset"})
        self.reticle.nextBallSprite = u.parseSpriteOpt(data, base, path, {"reticle", "nextBallSprite"})
        self.reticle.nextBallOffset = u.parseVec2Opt(data, base, path, {"reticle", "nextBallOffset"})
        self.reticle.radiusSprite = u.parseSpriteOpt(data, base, path, {"reticle", "radiusSprite"})
        self.reticle.colorFadeTime = u.parseNumberOpt(data, base, path, {"reticle", "colorFadeTime"})
        self.reticle.nextColorFadeTime = u.parseNumberOpt(data, base, path, {"reticle", "nextColorFadeTime"})
    end

    ---@type {sphereSwap: SoundEvent, sphereFill: SoundEvent}
    self.sounds = {}
    self.sounds.sphereSwap = u.parseSoundEvent(data, base, path, {"sounds", "sphereSwap"})
    self.sounds.sphereFill = u.parseSoundEvent(data, base, path, {"sounds", "sphereFill"})

    ---@type {sprite: Sprite, layer: string, fadeTime: number, renderingType: "full"|"cut"|"scale", colored: boolean}
    self.speedShotBeam = {}
    self.speedShotBeam.sprite = u.parseSprite(data, base, path, {"speedShotBeam", "sprite"})
    self.speedShotBeam.layer = u.parseStringOpt(data, base, path, {"speedShotBeam", "layer"}, "GameSpeedShotPsys")
    self.speedShotBeam.fadeTime = u.parseNumber(data, base, path, {"speedShotBeam", "fadeTime"})
    ---@type "full"|"cut"|"scale"
    self.speedShotBeam.renderingType = u.parseString(data, base, path, {"speedShotBeam", "renderingType"})
    self.speedShotBeam.colored = u.parseBoolean(data, base, path, {"speedShotBeam", "colored"})

    self.speedShotParticle = u.parseParticleEffectConfigOpt(data, base, path, {"speedShotParticle"})
    self.speedShotParticleLayer = u.parseStringOpt(data, base, path, {"speedShotParticleLayer"}, "GameSpeedShotPsys")
    self.shotSpeed = u.parseNumber(data, base, path, {"shotSpeed"})
    self.shotCooldown = u.parseNumberOpt(data, base, path, {"shotCooldown"}, 0)
    self.shotCooldownFade = u.parseNumberOpt(data, base, path, {"shotCooldownFade"}, 0)
    self.multishot = u.parseBooleanOpt(data, base, path, {"multishot"}, false)
    self.autofire = u.parseBooleanOpt(data, base, path, {"autofire"}, false)
    self.destroySphereOnFail = u.parseBooleanOpt(data, base, path, {"destroySphereOnFail"}, false)

    ---@type {duration: number, strength: number, speedShotDuration: number?, speedShotStrength: number?}
    if data.knockback then
        self.knockback = {}
        self.knockback.duration = u.parseNumber(data, base, path, {"knockback", "duration"})
        self.knockback.strength = u.parseNumber(data, base, path, {"knockback", "strength"})
        self.knockback.speedShotDuration = u.parseNumberOpt(data, base, path, {"knockback", "speedShotDuration"})
        self.knockback.speedShotStrength = u.parseNumberOpt(data, base, path, {"knockback", "speedShotStrength"})
    end

    self.hitboxOffset = u.parseVec2Opt(data, base, path, {"hitboxOffset"}, Vec2())
    self.hitboxSize = u.parseVec2(data, base, path, {"hitboxSize"})
end

---Injects functions to Resource Manager regarding this resource type.
---@param ResourceManager ResourceManager Resource Manager class to inject the functions to.
function ShooterConfig.inject(ResourceManager)
    ---@class ResourceManager
    ResourceManager = ResourceManager

    ---Retrieves a ShooterConfig by given path.
    ---@param reference string The path to the resource.
    ---@return ShooterConfig
    function ResourceManager:getShooterConfig(reference)
        return self:getResourceConfig(reference, "Shooter")
    end
end

return ShooterConfig