--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"
local Expression = require("src.Expression")

---@class SoundEventConfig
---@overload fun(data, path, isAnonymous):SoundEventConfig
local SoundEventConfig = class:derive("SoundEventConfig")

SoundEventConfig.metadata = {
    schemaPath = "sound_event.json"
}

---Constructs an instance of SoundEventConfig.
---@param data table Raw data from a file.
---@param path string? Path to the file. Used for error messages and saving data.
---@param isAnonymous boolean? If `true`, this resource is anonymous and its path is invalid for saving data.
---@param base SoundEventConfig? If specified, this resource extends the provided resource. Any missing fields are prepended from the base resource.
function SoundEventConfig:new(data, path, isAnonymous, base)
    local u = _ConfigUtils
    self._path = path
    self._alias = data._alias
    self._isAnonymous = isAnonymous

    base = base or {}

    self.sound = u.parseSoundOpt(data, base, path, {"sound"})
    self.loop = u.parseBooleanOpt(data, base, path, {"loop"}) == true
    self.flat = u.parseBooleanOpt(data, base, path, {"flat"}) == true
    self.volume = u.parseExprNumberOpt(data, base, path, {"volume"}) or Expression(1)
    self.pitch = u.parseExprNumberOpt(data, base, path, {"pitch"}) or Expression(1)
    self.playsPerFrame = u.parseIntegerOpt(data, base, path, {"playsPerFrame"})
    self.instances = u.parseIntegerOpt(data, base, path, {"instances"}) or 8

    self.sounds = {}
    if data.sounds then
        for i = 1, #data.sounds do
            self.sounds[i] = {}
            self.sounds[i].sound = u.parseSound(data, base, path, {"sounds", i, "sound"})
            self.sounds[i].loop = u.parseBooleanOpt(data, base, path, {"sounds", i, "loop"}) == true
            self.sounds[i].flat = u.parseBooleanOpt(data, base, path, {"sounds", i, "flat"}) == true
            self.sounds[i].volume = u.parseExprNumberOpt(data, base, path, {"sounds", i, "volume"}) or Expression(1)
            self.sounds[i].pitch = u.parseExprNumberOpt(data, base, path, {"sounds", i, "pitch"}) or Expression(1)
            self.sounds[i].playsPerFrame = u.parseIntegerOpt(data, base, path, {"sounds", i, "playsPerFrame"})
            self.sounds[i].instances = u.parseIntegerOpt(data, base, path, {"sounds", i, "instances"}) or 8

            self.sounds[i].conditions = {}
            if data.sounds[i].conditions then
                for j = 1, #data.sounds[i].conditions do
                    self.sounds[i].conditions[j] = u.parseExprBoolean(data, base, path, {"sounds", i, "conditions", j})
                end
            end
        end
    end
end

---Injects functions to Resource Manager regarding this resource type.
---@param ResourceManager ResourceManager Resource Manager class to inject the functions to.
function SoundEventConfig.inject(ResourceManager)
    ---@class ResourceManager
    ResourceManager = ResourceManager

    ---Retrieves a SoundEventConfig by given path.
    ---@param reference string The path to the resource.
    ---@return SoundEventConfig
    function ResourceManager:getSoundEventConfig(reference)
        return self:getResourceConfig(reference, "SoundEvent")
    end
end

return SoundEventConfig