--!!--
-- Auto-generated by DocLang Generator
-- REMOVE THIS COMMENT IF YOU MODIFY THIS FILE
-- in order to protect it from being overwritten!
--!!--

local class = require "com.class"

---@class SpriteConfig
---@overload fun(data, path, isAnonymous):SpriteConfig
local SpriteConfig = class:derive("SpriteConfig")

SpriteConfig.metadata = {
    schemaPath = "sprite.json"
}

---Constructs an instance of SpriteConfig.
---@param data table Raw data from a file.
---@param path string? Path to the file. Used for error messages and saving data.
---@param isAnonymous boolean? If `true`, this resource is anonymous and its path is invalid for saving data.
---@param base SpriteConfig? If specified, this resource extends the provided resource. Any missing fields are prepended from the base resource.
function SpriteConfig:new(data, path, isAnonymous, base)
    local u = _ConfigUtils
    self._path = path
    self._alias = data._alias
    self._isAnonymous = isAnonymous

    base = base or {}

    self.image = u.parseImage(data, base, path, {"image"})
    self.frameSize = u.parseVec2(data, base, path, {"frameSize"})

    ---@type {x1: integer, x2: integer, y1: integer, y2: integer}
    if data.frameCuts then
        self.frameCuts = {}
        self.frameCuts.x1 = u.parseInteger(data, base, path, {"frameCuts", "x1"})
        self.frameCuts.x2 = u.parseInteger(data, base, path, {"frameCuts", "x2"})
        self.frameCuts.y1 = u.parseInteger(data, base, path, {"frameCuts", "y1"})
        self.frameCuts.y2 = u.parseInteger(data, base, path, {"frameCuts", "y2"})
    end

    ---@type {pos: Vector2, frames: Vector2}[]
    self.states = {}
    for i = 1, #data.states do
        self.states[i] = {}
        self.states[i].pos = u.parseVec2(data, base, path, {"states", i, "pos"})
        self.states[i].frames = u.parseVec2(data, base, path, {"states", i, "frames"})
    end

    self.batched = u.parseBooleanOpt(data, base, path, {"batched"})
end

---Injects functions to Resource Manager regarding this resource type.
---@param ResourceManager ResourceManager Resource Manager class to inject the functions to.
function SpriteConfig.inject(ResourceManager)
    ---@class ResourceManager
    ResourceManager = ResourceManager

    ---Retrieves a SpriteConfig by given path.
    ---@param reference string The path to the resource.
    ---@return SpriteConfig
    function ResourceManager:getSpriteConfig(reference)
        return self:getResourceConfig(reference, "Sprite")
    end
end

return SpriteConfig